# Generated by Django 4.0.3 on 2022-03-21 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='eating_location',
            field=models.CharField(choices=[('None', 'None'), ('რესტორანში', 'რესტორანში'), ('ოფისში', 'ოფისში')], default='None', max_length=150),
        ),
    ]
