# Generated by Django 4.0.3 on 2022-03-21 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mealbrotherhood', '0001_initial'),
        ('accounts', '0002_alter_account_eating_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mealbrotherhood.restaurant'),
        ),
    ]
