# Generated by Django 4.0.3 on 2022-03-16 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_eating_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='eating_location',
            field=models.CharField(choices=[('in_restaurant', 'რესტორანში'), ('in_office', 'ოფისში')], default='in_restaurant', max_length=150),
        ),
    ]
