# Generated by Django 4.0.3 on 2022-03-16 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealbrotherhood', '0006_alter_restaurant_restaurant_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='restaurant_name',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
